### ISSUE TITLE
Deploying to Twitch

### ISSUE THREAD

**Issue by dangelojesse** [twitchdev/extensions-hello-world#1]
I was curious after using this example how do I actually go about bundling this up and deploying it to Twitch.  My local tests worked great but as soon as I tried the hosted test it just errors out.  I had just made a zip file of the root directory and uploaded it.

**Comment by davecusatis** [comment]
you only need to upload the front end assets to get it into hosted state.

**Comment by dangelojesse** [comment]
Awesome. Yeah after some more googling I had turned that up. Thanks for the help. I'll close this out.
