### ISSUE TITLE
curl command in docs

### ISSUE THREAD

**Issue by Chris-Cunningham** [twitchdev/extensions-hello-world#7]
I am not very familiar with curl, but the curl command given in the readme is 

`curl -H 'Client-ID: <client id>' -X GET 'https://api.twitch.tv/helix/users?login=<owner name>'`

This format did not work for me (newbie, on Windows) and the following format did, with double quotes for the header and no quotes at all for the actual url.

`curl -H "Client-ID: <client id>" -X GET https://api.twitch.tv/helix/users?login=<owner name>`

I don't know if this is just a typo in the readme (in which case I would have just tried to fix it) or if it depends on platform. Just trying to save future versions of me a little speedbump.

**Comment by Tenchumaru** [comment]
This was addressed in commit 0de5b7f.
